# Generated by Django 3.2.4 on 2021-06-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='company',
            new_name='company_id',
        ),
    ]
