# Generated by Django 3.2.4 on 2021-06-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_rename_company_receipt_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='company_id',
            new_name='company',
        ),
    ]
