# Generated by Django 2.2.5 on 2021-06-03 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_who_get_salary', to='accounts.Staff')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_who_pay_others', to='accounts.Staff')),
            ],
        ),
    ]
