# Generated by Django 3.2.4 on 2021-06-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='payer',
            new_name='payer_id',
        ),
    ]
